USE [IB15_DBVerwaltung_ps59_2]
GO

CREATE TABLE [elasticaudit].[T_DBCertTimestamps](
	[idDB] [int] NOT NULL,
	[dtSnapshot] [smalldatetime] NOT NULL,
 CONSTRAINT [PK_T_DBCertTimestamps] PRIMARY KEY CLUSTERED 
(
	[idDB] ASC,
	[dtSnapshot] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


