CREATE OR REPLACE PROCEDURE AUTH_DB2_LUW_REPORT.USP_LATECERTLIST_PARA (
    IN P_DB_CMDB_NAME	VARCHAR(100),
    IN P_TIMESTAMP	VARCHAR(40) )
  SPECIFIC USP_LATECERTLIST_PARA
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
BEGIN 
  	DECLARE cur CURSOR WITH RETURN FOR 
  	SELECT RPAD(VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS'),32) LateCert, sp.SNAP_TS LATECERT_DATE
	FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_luw_snapshots sp 
	WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
		AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') < TRIM(P_TIMESTAMP)
	GROUP BY sp.SNAP_TS
	UNION ALL
	SELECT NULL LateCert, NULL LATECERT_DATE FROM sysibm.sysdummy1
	ORDER BY 2 DESC;

  OPEN cur;
  -- Optional: exception expressions
  -- EXCEPTION 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
  -- ... 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
END