CREATE OR REPLACE PROCEDURE AUTH_DB2_LUW_REPORT.USP_DATABASELIST_PARA ( IN P_USERID VARCHAR(20) )
  SPECIFIC USP_DATABASELIST_PARA
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
BEGIN 
  DECLARE cur CURSOR WITH RETURN FOR
 	SELECT DISTINCT RTRIM(dbas.DB_CMDB_NAME) AS DB_NAME --RPAD(dbas.DB_CMDB_NAME,75) DB_NAME
	FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DATABASE dbas
	WHERE ( 1 = (select 1 from AUTH_DB2_LUW_REPORT.VW_DB2_LUW_ADMINS WHERE USERID in (TRIM(P_USERID), 'LAN\' || TRIM(P_USERID)) FETCH FIRST 1 ROW ONLY) or
		dbas.DBA_1=TRIM(P_USERID) or
		dbas.DBA_2=TRIM(P_USERID) or
		dbas.DBA_3=TRIM(P_USERID) or
		dbas.DATA_ENABLER_1=TRIM(P_USERID) or
		dbas.DATA_ENABLER_2=TRIM(P_USERID) or
		dbas.DATA_ENABLER_3=TRIM(P_USERID) or
		dbas.DATA_OWNER=TRIM(P_USERID) or
		dbas.DATA_STEWARD_1=TRIM(P_USERID) or
		dbas.DATA_STEWARD_2=TRIM(P_USERID) or
		dbas.DATA_STEWARD_3=TRIM(P_USERID) 
	);
		
	OPEN cur;		
  -- Optional: exception expressions
  -- EXCEPTION 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
  -- ... 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
END