CREATE OR REPLACE PROCEDURE AUTH_DB2_LUW_REPORT.USP_SNAPSHOTLIST_PARA ( IN P_DB_CMDB_NAME VARCHAR(100) )
  SPECIFIC USP_SNAPSHOTLIST_PARA
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
BEGIN 
  DECLARE cur CURSOR WITH RETURN FOR
 	SELECT RPAD(VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS'),32) dtTimestamp, sp.SNAP_TS SNAPSHOT_DATE
	FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_luw_snapshots sp 
	WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
	GROUP BY sp.SNAP_TS
	ORDER BY 2 DESC;
		
	OPEN cur;
  -- Optional: exception expressions
  -- EXCEPTION 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
  -- ... 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
END