CREATE OR REPLACE PROCEDURE AUTH_DB2_LUW_REPORT.USP_OBJECTPERM_DATA (
    IN P_DB_CMDB_NAME	VARCHAR(100),
    IN P_TIMESTAMP	VARCHAR(40),
    IN P_PREVTIMESTAMP	VARCHAR(40),
    IN P_PERSONROLE	VARCHAR(40),
    IN P_WHITELIST	SMALLINT )
  SPECIFIC USP_OBJECTPERM_DATA
  DYNAMIC RESULT SETS 1
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
BEGIN 
	DECLARE cur CURSOR WITH RETURN FOR 
	WITH curr_global as (
	WITH dbperm_ as (
--unpivot for db_permission 
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 	   
	   'BINDADD' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.BINDADDAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
		'CREATETAB' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.CREATETABAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
		'DBADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.DBADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'EXTERNALROUTINE' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.EXTERNALROUTINEAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'IMPLSCHEMA' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.IMPLSCHEMAAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'LOAD' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.LOADAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'NOFENCE' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.NOFENCEAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'QUIESCECONNECT' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.QUIESCECONNECTAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'LIBRARYADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.LIBRARYADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'SECURITYADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.SECURITYADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SQLADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.SQLADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'WLMADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.WLMADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'EXPLAIN' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.EXPLAINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DATAACCESS' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.DATAACCESSAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'ACCESSCTRL' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.ACCESSCTRLAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	'CREATESECURE' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND  sp.CREATESECUREAUTH != 'N'
)
, tabperm_ as (
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'CONTROL' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.CONTROLAUTH != 'N'
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'ALTER' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.ALTERAUTH != 'N'   
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'DELETE' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.DELETEAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'INDEX' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp

WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.INDEXAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS,  
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'INSERT' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.INSERTAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS,  
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'REF' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.REFAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'SELECT' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.SELECTAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS,  
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'UPDATE' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.UPDATEAUTH != 'N'
),
schperm_ as (
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'ALTERIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.ALTERINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'CREATEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.CREATEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DROPIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.DROPINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SELECTIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.SELECTINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'INSERTIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.INSERTINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE,  sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'UPDATEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.UPDATEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DELETEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.DELETEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE,  sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'EXECUTEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.EXECUTEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SCHEMAADM' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.SCHEMAADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'ACCESSCTRL' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.ACCESSCTRLAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DATAACCESS' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.DATAACCESSAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'LOAD' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.LOADAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SCHEMARCAC' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
     AND sp.SCHEMARCACAUTH != 'N'
),
colperm_ as (
SELECT sp. DB_CMDB_NAME, sp.GRANTEE, sp.TIMESTAMP SNAP_TS,
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SELECT' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   sp.COLNAME COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_COLAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.TIMESTAMP,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
)
 SELECT rol.GRANTEE USERNAME, 
		CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
		 				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
		ELSE NULL END USERTYPE, 
		rol.ROLENAME,
		'GRANT' ACCESSTYPE,
		dbperm.PRIVILAGENAME,
		dbperm.TABLE_TYPE,
		dbperm.SCHEMANAME,
		dbperm.OBJECTNAME,
		dbperm.COLUMNNAME
 FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
  INNER JOIN dbperm_ dbperm  
   ON trim(rol.DB_CMDB_NAME) = trim(dbperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = dbperm.SNAP_TS
   		AND (rol.GRANTEE = dbperm.GRANTEE OR rol.ROLENAME  = dbperm.GRANTEE)
 WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)  
    AND TRIM(P_PERSONROLE) != 'DataSteward'
 UNION ALL
 SELECT rol.GRANTEE USERNAME, 
	   CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   rol.ROLENAME,
	   'GRANT' ACCESSTYPE,
	   tabperm.PRIVILAGENAME,
	   tabperm.TABLE_TYPE,
	   tabperm.SCHEMANAME,
	   tabperm.OBJECTNAME,
	   tabperm.COLUMNNAME
 FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
 INNER JOIN tabperm_ tabperm 
   ON trim(rol.DB_CMDB_NAME) = trim(tabperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = tabperm.SNAP_TS
   		AND (rol.GRANTEE = tabperm.GRANTEE OR rol.ROLENAME  = tabperm.GRANTEE)
 WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)  
    AND TRIM(P_PERSONROLE) != 'DataSteward'
 UNION ALL
  SELECT rol.GRANTEE USERNAME, 
	   CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   rol.ROLENAME,
	   'GRANT' ACCESSTYPE,
	   schperm.PRIVILAGENAME,
	   schperm.TABLE_TYPE,
	   schperm.SCHEMANAME,
	   schperm.OBJECTNAME,
	   schperm.COLUMNNAME
 FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
 INNER JOIN schperm_ schperm
   ON trim(rol.DB_CMDB_NAME) = trim(schperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = schperm.SNAP_TS
   		AND (rol.GRANTEE = schperm.GRANTEE OR rol.ROLENAME  = schperm.GRANTEE)
 WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP) 
    AND TRIM(P_PERSONROLE) != 'DataSteward'
UNION ALL
SELECT rol.GRANTEE USERNAME, 
	   CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   rol.ROLENAME,
	   'GRANT' ACCESSTYPE,
	   colperm.PRIVILAGENAME,
	   colperm.TABLE_TYPE,
	   colperm.SCHEMANAME,
	   colperm.OBJECTNAME,
	   ISNULL(colperm.COLUMNNAME,'*') COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
INNER JOIN colperm_ colperm
	ON trim(rol.DB_CMDB_NAME) = trim(colperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = colperm.SNAP_TS
   		AND (rol.GRANTEE = colperm.GRANTEE OR rol.ROLENAME  = colperm.GRANTEE)
WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_TIMESTAMP)
    AND TRIM(P_PERSONROLE) != 'DataSteward'
    ),
    
    
    
    prev_global as (
    
    
    
    WITH dbperm as (
--unpivot for db_permission 
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 	   
	   'BINDADD' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.BINDADDAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'CONNECT' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.CONNECTAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
		'CREATETAB' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.CREATETABAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
		'DBADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.DBADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'EXTERNALROUTINE' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.EXTERNALROUTINEAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'IMPLSCHEMA' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.IMPLSCHEMAAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'LOAD' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.LOADAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'NOFENCE' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.NOFENCEAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'QUIESCECONNECT' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.QUIESCECONNECTAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'LIBRARYADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.LIBRARYADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'SECURITYADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.SECURITYADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SQLADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.SQLADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'WLMADM' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.WLMADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'EXPLAIN' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.EXPLAINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DATAACCESS' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.DATAACCESSAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'ACCESSCTRL' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.ACCESSCTRLAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	'CREATESECURE' PRIVILAGENAME, 'DATABASE' TABLE_TYPE, '*' SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_DBAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND  sp.CREATESECUREAUTH != 'N'
)
, tabperm as (
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'CONTROL' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.CONTROLAUTH != 'N'
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'ALTER' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.ALTERAUTH != 'N'   
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'DELETE' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.DELETEAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'INDEX' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp

WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.INDEXAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS,  
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'INSERT' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.INSERTAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS,  
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'REF' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.REFAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS, 
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE,
	   'SELECT' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.SELECTAUTH != 'N'  
UNION ALL
SELECT sp.DB_CMDB_NAME, sp.GRANTEE, sp.SNAP_TS,  
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'UPDATE' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_TABAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.UPDATEAUTH != 'N'
),
schperm as (
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'ALTERIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.ALTERINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'CREATEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.CREATEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DROPIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.DROPINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SELECTIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.SELECTINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'INSERTIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.INSERTINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE,  sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'UPDATEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.UPDATEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DELETEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.DELETEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE,  sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'EXECUTEIN' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.EXECUTEINAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SCHEMAADM' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.SCHEMAADMAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'ACCESSCTRL' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.ACCESSCTRLAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'DATAACCESS' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.DATAACCESSAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'LOAD' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.LOADAUTH != 'N'
UNION ALL
SELECT DB_CMDB_NAME, GRANTEE, sp.SNAP_TS,
	   CASE GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SCHEMARCAC' PRIVILAGENAME, 'SCHEMA' TABLE_TYPE, sp.SCHEMANAME, '*' OBJECTNAME, '*' COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_SCHEMAAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
     AND sp.SCHEMARCACAUTH != 'N'
),
colperm as (
SELECT sp. DB_CMDB_NAME, sp.GRANTEE, sp.TIMESTAMP SNAP_TS,
	   CASE sp.GRANTEETYPE 	WHEN 'R' THEN 'DATABASE_ROLE'
	   				    	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   'SELECT' PRIVILAGENAME, 
	   'TABLE' TABLE_TYPE, 
	   sp.TABSCHEMA SCHEMANAME, 
	   sp.TABNAME OBJECTNAME,
	   sp.COLNAME COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_COLAUTH sp
WHERE trim(sp.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
     AND VARCHAR_FORMAT(sp.TIMESTAMP,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
)
 SELECT rol.GRANTEE USERNAME, 
		CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
		 				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
		ELSE NULL END USERTYPE, 
		rol.ROLENAME,
		'GRANT' ACCESSTYPE,
		dbperm.PRIVILAGENAME,
		dbperm.TABLE_TYPE,
		dbperm.SCHEMANAME,
		dbperm.OBJECTNAME,
		dbperm.COLUMNNAME
 FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
  INNER JOIN dbperm  
   ON trim(rol.DB_CMDB_NAME) = trim(dbperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = dbperm.SNAP_TS
   		AND (rol.GRANTEE = dbperm.GRANTEE OR rol.ROLENAME  = dbperm.GRANTEE)
 WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)  
    AND TRIM(P_PERSONROLE) != 'DataSteward'
 UNION ALL
 SELECT rol.GRANTEE USERNAME, 
	   CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   rol.ROLENAME,
	   'GRANT' ACCESSTYPE,
	   tabperm.PRIVILAGENAME,
	   tabperm.TABLE_TYPE,
	   tabperm.SCHEMANAME,
	   tabperm.OBJECTNAME,
	   tabperm.COLUMNNAME
 FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
 INNER JOIN tabperm  
   ON trim(rol.DB_CMDB_NAME) = trim(tabperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = tabperm.SNAP_TS
   		AND (rol.GRANTEE = tabperm.GRANTEE OR rol.ROLENAME  = tabperm.GRANTEE)
 WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)  
    AND TRIM(P_PERSONROLE) != 'DataSteward'
 UNION ALL
  SELECT rol.GRANTEE USERNAME, 
	   CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   rol.ROLENAME,
	   'GRANT' ACCESSTYPE,
	   schperm.PRIVILAGENAME,
	   schperm.TABLE_TYPE,
	   schperm.SCHEMANAME,
	   schperm.OBJECTNAME,
	   schperm.COLUMNNAME
 FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
 INNER JOIN schperm  
   ON trim(rol.DB_CMDB_NAME) = trim(schperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = schperm.SNAP_TS
   		AND (rol.GRANTEE = schperm.GRANTEE OR rol.ROLENAME  = schperm.GRANTEE)
 WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
    AND TRIM(P_PERSONROLE) != 'DataSteward'
UNION ALL
SELECT rol.GRANTEE USERNAME, 
	   CASE rol.GRANTEETYPE WHEN 'R' THEN 'DATABASE_ROLE'
	   				    WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
	   ELSE NULL END USERTYPE, 
	   rol.ROLENAME,
	   'GRANT' ACCESSTYPE,
	   colperm.PRIVILAGENAME,
	   colperm.TABLE_TYPE,
	   colperm.SCHEMANAME,
	   colperm.OBJECTNAME,
	   ISNULL(colperm.COLUMNNAME,'*') COLUMNNAME
FROM AUTH_DB2_LUW_REPORT.VW_REPORT_DB2_LUW_ROLEAUTH rol
INNER JOIN colperm  
	ON trim(rol.DB_CMDB_NAME) = trim(colperm.DB_CMDB_NAME)
   		AND rol.SNAP_TS = colperm.SNAP_TS
   		AND (rol.GRANTEE = colperm.GRANTEE OR rol.ROLENAME  = colperm.GRANTEE)
WHERE trim(rol.DB_CMDB_NAME) = trim(P_DB_CMDB_NAME)
    AND VARCHAR_FORMAT(rol.SNAP_TS,'DD.MM.YYYY HH24:MI:SS') = TRIM(P_PREVTIMESTAMP)
    AND TRIM(P_PERSONROLE) != 'DataSteward'
 ORDER BY COLUMNNAME DESC
    )
    SELECT  
            'Global permission' Global, 
            ISNULL(curr.USERNAME, prev.USERNAME)			            	as username, 
            ISNULL(curr.ROLENAME, prev.ROLENAME)							as rolename,
            ISNULL(curr.SCHEMANAME, prev.SCHEMANAME)						as schemaname,
            ISNULL(curr.TABLE_TYPE, prev.TABLE_TYPE)				    	as table_type,		
            case ISNULL(curr.USERTYPE, prev.USERTYPE)	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
                                                    	when 'R' then 'DATABASE_ROLE'
            else ISNULL(curr.USERTYPE, prev.USERTYPE) end              	as usertype,
            ISNULL(curr.ACCESSTYPE, prev.ACCESSTYPE)						as AccessType,
            ISNULL(curr.PRIVILAGENAME, prev.PRIVILAGENAME)		    		as Privilege,
            ISNULL(curr.OBJECTNAME, prev.OBJECTNAME)				    	as Objectname,
            ISNULL(curr.COLUMNNAME, prev.COLUMNNAME)						as ColumnName,
            case when curr.PRIVILAGENAME is null and prev.PRIVILAGENAME is not null then 'DEL'
                 when prev.PRIVILAGENAME is null and curr.PRIVILAGENAME is not null then 'NEW'
            else 'SAME' end sign_compare
        FROM curr_global curr
        FULL OUTER JOIN prev_global prev 
            ON ISNULL(prev.USERNAME,'')=ISNULL(curr.USERNAME,'') 
            	AND ISNULL(prev.ROLENAME,'')=ISNULL(curr.ROLENAME,'') 
            	AND ISNULL(prev.SCHEMANAME,'')=ISNULL(curr.SCHEMANAME,'') 
            	AND ISNULL(prev.TABLE_TYPE,'')=ISNULL(curr.TABLE_TYPE,'') 
            	AND ISNULL(prev.OBJECTNAME,'')=ISNULL(curr.OBJECTNAME,'')
            	AND ISNULL(prev.COLUMNNAME,'')=ISNULL(curr.COLUMNNAME,'')
            	AND ISNULL(prev.USERTYPE,'')=ISNULL(curr.USERTYPE,'') 
            	and ISNULL(prev.ACCESSTYPE,'')=ISNULL(curr.ACCESSTYPE,'') 
            	and ISNULL(prev.PRIVILAGENAME,'')=ISNULL(curr.PRIVILAGENAME,'')
        WHERE curr.PRIVILAGENAME is not null --without DELETED permission
		AND (ISNULL(P_WHITELIST,0)=0
                OR (not exists (select 1 from AUTH_DB2_LUW_REPORT.VW_DB2_LUW_ADMINS where USERID = ISNULL(curr.USERNAME, prev.USERNAME) ))
            )
        GROUP BY
        'Global permission' , 
            ISNULL(curr.USERNAME, prev.USERNAME)			            	, 
            ISNULL(curr.ROLENAME, prev.ROLENAME)							,
            ISNULL(curr.SCHEMANAME, prev.SCHEMANAME)					,
            ISNULL(curr.TABLE_TYPE, prev.TABLE_TYPE)				  ,		
            case ISNULL(curr.USERTYPE, prev.USERTYPE)	WHEN 'G' THEN 'DATABASE_GROUP' WHEN 'U' THEN 'DATABASE_USER'
                                                    	when 'R' then 'DATABASE_ROLE'
            else ISNULL(curr.USERTYPE, prev.USERTYPE) end              	,
            ISNULL(curr.ACCESSTYPE, prev.ACCESSTYPE)					,
            ISNULL(curr.PRIVILAGENAME, prev.PRIVILAGENAME)		,
            ISNULL(curr.OBJECTNAME, prev.OBJECTNAME)				  ,
            ISNULL(curr.COLUMNNAME, prev.COLUMNNAME)					,
            case when curr.PRIVILAGENAME is null and prev.PRIVILAGENAME is not null then 'DEL'
                 when prev.PRIVILAGENAME is null and curr.PRIVILAGENAME is not null then 'NEW'
            else 'SAME' end 
        ORDER BY sign_compare, --strFullInstanceName, 
        username, rolename, table_type, AccessType, Privilege, schemaname, Objectname, ColumnName;
  OPEN cur;
  -- Optional: exception expressions
  -- EXCEPTION 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
  -- ... 
  -- WHEN { exception-condition } THEN { statement; } ... { statement; } 
END